// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkGroupExists = `-- name: CheckGroupExists :one
SELECT EXISTS(SELECT 1 FROM grp WHERE id = $1) as exists
`

func (q *Queries) CheckGroupExists(ctx context.Context, id []byte) (bool, error) {
	row := q.db.QueryRow(ctx, checkGroupExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO grp (id, name, description, owner_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateGroupParams struct {
	ID          []byte `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	OwnerID     []byte `json:"owner_id"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OwnerID,
	)
	var id []byte
	err := row.Scan(&id)
	return id, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM grp
WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT name, description, created_at, id, owner_id FROM grp
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGroup(ctx context.Context, id []byte) (*Grp, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Grp
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.ID,
		&i.OwnerID,
	)
	return &i, err
}

const getGroups = `-- name: GetGroups :many
SELECT 
    g.name, g.description, g.created_at, g.id, g.owner_id,
    mem.role,
    mem.joined_at,
    m.content AS last_message_content,
    m.created_at AS last_message_created_at,
    last_message_id,
    m.sender_id AS last_message_sender_id,
    m.type AS last_message_type,
    u.name AS last_message_sender_name
FROM grp AS g
INNER JOIN grp_membership AS mem
    ON g.id = mem.grp_id
LEFT JOIN (
    SELECT DISTINCT ON (grp_id)
        grp_id,
        id AS last_message_id
    FROM message
    ORDER BY grp_id, id DESC
) AS lm 
    ON lm.grp_id = g.id
LEFT JOIN message as m
    ON m.id = lm.last_message_id
LEFT JOIN usr AS u
    ON u.id = m.sender_id
WHERE mem.usr_id  = $1
ORDER BY lm.last_message_id DESC NULLS LAST
`

type GetGroupsRow struct {
	Name                  string             `json:"name"`
	Description           string             `json:"description"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	ID                    []byte             `json:"id"`
	OwnerID               []byte             `json:"owner_id"`
	Role                  string             `json:"role"`
	JoinedAt              pgtype.Timestamptz `json:"joined_at"`
	LastMessageContent    pgtype.Text        `json:"last_message_content"`
	LastMessageCreatedAt  pgtype.Timestamptz `json:"last_message_created_at"`
	LastMessageID         []byte             `json:"last_message_id"`
	LastMessageSenderID   []byte             `json:"last_message_sender_id"`
	LastMessageType       pgtype.Text        `json:"last_message_type"`
	LastMessageSenderName pgtype.Text        `json:"last_message_sender_name"`
}

// Returns detailed information about all groups the user is part of
// Also sorts the returned groups by the last message sent timestamp
// Also returns the last message (if any) of the group
// Also joins with the user table, and returns the sender name, so that it can be directly rendered in the sidebar
func (q *Queries) GetGroups(ctx context.Context, usrID []byte) ([]*GetGroupsRow, error) {
	rows, err := q.db.Query(ctx, getGroups, usrID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetGroupsRow
	for rows.Next() {
		var i GetGroupsRow
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ID,
			&i.OwnerID,
			&i.Role,
			&i.JoinedAt,
			&i.LastMessageContent,
			&i.LastMessageCreatedAt,
			&i.LastMessageID,
			&i.LastMessageSenderID,
			&i.LastMessageType,
			&i.LastMessageSenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupById = `-- name: UpdateGroupById :one
UPDATE grp 
SET
    name = coalesce($1, name),
    description = coalesce($2, description)
WHERE id = $3
RETURNING name, description, created_at, id, owner_id
`

type UpdateGroupByIdParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          []byte      `json:"id"`
}

func (q *Queries) UpdateGroupById(ctx context.Context, arg UpdateGroupByIdParams) (*Grp, error) {
	row := q.db.QueryRow(ctx, updateGroupById, arg.Name, arg.Description, arg.ID)
	var i Grp
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.ID,
		&i.OwnerID,
	)
	return &i, err
}
