// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: groups.sql

package db

import (
	"context"
)

const getGroup = `-- name: GetGroup :one
SELECT id, name, description, created_at FROM grp
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGroup(ctx context.Context, id int64) (Grp, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Grp
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
