// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO grp (id, name, description)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateGroupParams struct {
	ID          []byte `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.ID, arg.Name, arg.Description)
	var id []byte
	err := row.Scan(&id)
	return id, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM grp
WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT name, description, created_at, id FROM grp
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGroup(ctx context.Context, id []byte) (*Grp, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Grp
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.ID,
	)
	return &i, err
}

const getGroups = `-- name: GetGroups :many
SELECT name, description, created_at, id FROM grp
`

func (q *Queries) GetGroups(ctx context.Context) ([]*Grp, error) {
	rows, err := q.db.Query(ctx, getGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Grp
	for rows.Next() {
		var i Grp
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupById = `-- name: UpdateGroupById :one
UPDATE grp 
SET
    name = coalesce($1, name),
    description = coalesce($2, description)
WHERE id = $3
RETURNING name, description, created_at, id
`

type UpdateGroupByIdParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          []byte      `json:"id"`
}

func (q *Queries) UpdateGroupById(ctx context.Context, arg UpdateGroupByIdParams) (*Grp, error) {
	row := q.db.QueryRow(ctx, updateGroupById, arg.Name, arg.Description, arg.ID)
	var i Grp
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.ID,
	)
	return &i, err
}
