// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: membership.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkMembership = `-- name: CheckMembership :one

SELECT EXISTS(
    SELECT 1 FROM grp_membership
    WHERE
        grp_id = $1
            AND
        usr_id = $2
    )
`

type CheckMembershipParams struct {
	GrpID []byte `json:"grp_id"`
	UsrID []byte `json:"usr_id"`
}

// Check if user is part of a group
func (q *Queries) CheckMembership(ctx context.Context, arg CheckMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkMembership, arg.GrpID, arg.UsrID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createMembership = `-- name: CreateMembership :one

INSERT INTO grp_membership (grp_id, usr_id, role)
VALUES ($1, $2, 'member')
RETURNING joined_at
`

type CreateMembershipParams struct {
	GrpID []byte `json:"grp_id"`
	UsrID []byte `json:"usr_id"`
}

// Add a user to a group
func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.GrpID, arg.UsrID)
	var joined_at pgtype.Timestamptz
	err := row.Scan(&joined_at)
	return joined_at, err
}

const deleteMembership = `-- name: DeleteMembership :exec

DELETE FROM grp_membership
WHERE
    grp_id = $1
        AND
    usr_id = $2
`

type DeleteMembershipParams struct {
	GrpID []byte `json:"grp_id"`
	UsrID []byte `json:"usr_id"`
}

// Remove a user from a group
func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.GrpID, arg.UsrID)
	return err
}

const getGroupMembersWithName = `-- name: GetGroupMembersWithName :many
SELECT m.grp_id, m.usr_id, m.role, m.joined_at, u.username, u.name FROM 
grp_membership AS m 
INNER JOIN usr AS u
ON m.usr_id = u.id
WHERE grp_id = $1
`

type GetGroupMembersWithNameRow struct {
	GrpID    []byte             `json:"grp_id"`
	UsrID    []byte             `json:"usr_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
	Username string             `json:"username"`
	Name     string             `json:"name"`
}

func (q *Queries) GetGroupMembersWithName(ctx context.Context, grpID []byte) ([]*GetGroupMembersWithNameRow, error) {
	rows, err := q.db.Query(ctx, getGroupMembersWithName, grpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetGroupMembersWithNameRow
	for rows.Next() {
		var i GetGroupMembersWithNameRow
		if err := rows.Scan(
			&i.GrpID,
			&i.UsrID,
			&i.Role,
			&i.JoinedAt,
			&i.Username,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMemberships = `-- name: GetGroupMemberships :many

SELECT grp_id, usr_id, role, joined_at FROM grp_membership
WHERE
grp_id = $1
`

// Get all users in a group
func (q *Queries) GetGroupMemberships(ctx context.Context, grpID []byte) ([]*GrpMembership, error) {
	rows, err := q.db.Query(ctx, getGroupMemberships, grpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GrpMembership
	for rows.Next() {
		var i GrpMembership
		if err := rows.Scan(
			&i.GrpID,
			&i.UsrID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserMemberships = `-- name: GetUserMemberships :many

SELECT grp_id, usr_id, role, joined_at FROM grp_membership
WHERE
usr_id = $1
`

// Get all groups the user is a part of
func (q *Queries) GetUserMemberships(ctx context.Context, usrID []byte) ([]*GrpMembership, error) {
	rows, err := q.db.Query(ctx, getUserMemberships, usrID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GrpMembership
	for rows.Next() {
		var i GrpMembership
		if err := rows.Scan(
			&i.GrpID,
			&i.UsrID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
