// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (id, type, grp_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateMessageParams struct {
	ID      []byte `json:"id"`
	Type    string `json:"type"`
	GrpID   []byte `json:"grp_id"`
	Content string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.Type,
		arg.GrpID,
		arg.Content,
	)
	var id []byte
	err := row.Scan(&id)
	return id, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM message
WHERE 
    id = $1
        AND
    grp_id = $2
`

type DeleteMessageParams struct {
	ID    []byte `json:"id"`
	GrpID []byte `json:"grp_id"`
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) error {
	_, err := q.db.Exec(ctx, deleteMessage, arg.ID, arg.GrpID)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, type, grp_id, created_at, content FROM message
WHERE
    id = $1
        AND
    grp_id = $2
LIMIT 1
`

type GetMessageParams struct {
	ID    []byte `json:"id"`
	GrpID []byte `json:"grp_id"`
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (*Message, error) {
	row := q.db.QueryRow(ctx, getMessage, arg.ID, arg.GrpID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.GrpID,
		&i.CreatedAt,
		&i.Content,
	)
	return &i, err
}

const getMessagesInGroup = `-- name: GetMessagesInGroup :many
SELECT id, type, grp_id, created_at, content FROM message
WHERE
    grp_id = $1
AND
    ($2::bytea IS NULL OR id < $2::bytea)
ORDER BY id DESC
LIMIT $3
`

type GetMessagesInGroupParams struct {
	GrpID  []byte `json:"grp_id"`
	Before []byte `json:"before"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetMessagesInGroup(ctx context.Context, arg GetMessagesInGroupParams) ([]*Message, error) {
	rows, err := q.db.Query(ctx, getMessagesInGroup, arg.GrpID, arg.Before, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.GrpID,
			&i.CreatedAt,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
