// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Grp struct {
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ID          []byte             `json:"id"`
}

type Message struct {
	ID        []byte             `json:"id"`
	Type      string             `json:"type"`
	GrpID     []byte             `json:"grp_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Content   string             `json:"content"`
}

type Token struct {
	Hash      []byte             `json:"hash"`
	UsrID     []byte             `json:"usr_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Expiry    pgtype.Timestamptz `json:"expiry"`
	Scope     string             `json:"scope"`
}

type Usr struct {
	ID        []byte             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Name      string             `json:"name"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Password  []byte             `json:"password"`
	Activated bool               `json:"activated"`
}
