// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	GetGroup(ctx context.Context, id int64) (Grp, error)
}

var _ Querier = (*Queries)(nil)
