// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO token
    (hash, usr_id, expiry, scope)
VALUES (
        $1,
        $2,
        $3,
        $4
)
`

type CreateTokenParams struct {
	Hash   []byte             `json:"hash"`
	UsrID  []byte             `json:"usr_id"`
	Expiry pgtype.Timestamptz `json:"expiry"`
	Scope  string             `json:"scope"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.Exec(ctx, createToken,
		arg.Hash,
		arg.UsrID,
		arg.Expiry,
		arg.Scope,
	)
	return err
}

const deleteTokenByHash = `-- name: DeleteTokenByHash :exec
DELETE FROM token
WHERE hash = $1
`

func (q *Queries) DeleteTokenByHash(ctx context.Context, hash []byte) error {
	_, err := q.db.Exec(ctx, deleteTokenByHash, hash)
	return err
}

const deleteTokensByUserId = `-- name: DeleteTokensByUserId :exec
DELETE FROM token
WHERE
    usr_id = $1
        AND
    scope = $2
`

type DeleteTokensByUserIdParams struct {
	UsrID []byte `json:"usr_id"`
	Scope string `json:"scope"`
}

func (q *Queries) DeleteTokensByUserId(ctx context.Context, arg DeleteTokensByUserIdParams) error {
	_, err := q.db.Exec(ctx, deleteTokensByUserId, arg.UsrID, arg.Scope)
	return err
}

const verifyToken = `-- name: VerifyToken :one
SELECT usr_id FROM token
WHERE
    scope = $1
    AND hash = $2
    AND expiry > NOW()
`

type VerifyTokenParams struct {
	Scope string `json:"scope"`
	Hash  []byte `json:"hash"`
}

func (q *Queries) VerifyToken(ctx context.Context, arg VerifyTokenParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, verifyToken, arg.Scope, arg.Hash)
	var usr_id []byte
	err := row.Scan(&usr_id)
	return usr_id, err
}
