// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO usr (id, name, username, email, password, activated)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at
`

type CreateUserParams struct {
	ID        []byte `json:"id"`
	Name      string `json:"name"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Password  []byte `json:"password"`
	Activated bool   `json:"activated"`
}

type CreateUserRow struct {
	ID        []byte             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Activated,
	)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, name, username, email, password, activated FROM usr
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*Usr, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i Usr
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Activated,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, created_at, name, username, email, password, activated FROM usr
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*Usr, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i Usr
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Activated,
	)
	return &i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE usr
SET
    name = coalesce($1, name),
    username = coalesce($2, username),
    email = coalesce($3, email),
    password = coalesce($4, password),
    activated = coalesce($5, activated)
WHERE id = $6
RETURNING id, created_at, name, username, email, password, activated
`

type UpdateUserParams struct {
	Name      pgtype.Text `json:"name"`
	Username  pgtype.Text `json:"username"`
	Email     pgtype.Text `json:"email"`
	Password  []byte      `json:"password"`
	Activated pgtype.Bool `json:"activated"`
	ID        []byte      `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*Usr, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Activated,
		arg.ID,
	)
	var i Usr
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Activated,
	)
	return &i, err
}
