ALTER INDEX IF EXISTS idx_grp_id RENAME TO idx_public_id;

ALTER TABLE grp DROP CONSTRAINT IF EXISTS pk_grp;

ALTER TABLE grp RENAME COLUMN id TO public_id;

ALTER TABLE grp ADD COLUMN id BIGSERIAL;

ALTER TABLE grp ADD CONSTRAINT Pk_grp PRIMARY KEY (id);