ALTER TABLE grp DROP CONSTRAINT IF EXISTS Pk_grp;

ALTER TABLE grp DROP COLUMN IF EXISTS id;

ALTER TABLE grp RENAME COLUMN public_id TO id;

ALTER TABLE grp ADD CONSTRAINT pk_grp PRIMARY KEY (id);

ALTER INDEX IF EXISTS idx_public_id RENAME TO idx_grp_id;